spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
        cache: false
  
  datasource:
        url: "jdbc:mariadb://localhost:3306/jpatest"
        username: root
        password: 1234
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
  jackson:
    time-zone : UTC
    serialization:
                    WRITE_DATES_AS_TIMESTAMPS: false
   
                              
## App Properties
app:
    jwtSecret : JWTSuperSecretKey
    jwtExpirationInMs : 604800000


server:
  port: 8080
